### ISSUE TITLE
部分B站视频无法下载，错误信息url parse failed

### ISSUE THREAD

**Issue by jazx463684061** [iawia002/lux#1000]
情况如图
![1](https://user-images.githubusercontent.com/59435345/149911156-9f2908bc-714f-4800-94d1-f0cac328061f.png)
图中视频链接和相同情况链接如下
https://www.bilibili.com/video/BV1p34y1i7LS
https://www.bilibili.com/video/BV12S4y1d7A6
https://www.bilibili.com/video/BV16v4y1o7zf
https://www.bilibili.com/video/BV1kv4y1Z7ZD
https://www.bilibili.com/video/BV1Qh411C7UU

**Comment by picasso250** [comment]
extractors\bilibili\bilibili.go
getMultiPageData
json 解不出来。

或许因为BV1p34y1i7LS实质上是个play list

**Comment by jazx463684061** [comment]
> extractors\bilibili\bilibili.go getMultiPageData json 解不出来。
> 
> 或许因为BV1p34y1i7LS实质上是个play list

是的你说的情况，测试了一下真实地址是播放列表样式的地址，但是又好像不是真的播放地址。比如https://www.bilibili.com/video/BV1p34y1i7LS的真实地址是https://www.bilibili.com/bangumi/play/ep466250
使用-p url下载会一直卡住，不加-p可以完成下载
![2](https://user-images.githubusercontent.com/59435345/149973722-addb32b9-a1bd-47ec-bbe6-2527def1b7fb.png)
![3](https://user-images.githubusercontent.com/59435345/149973737-d958c5df-9b58-457a-8a03-c6371e595e29.png)
