### ISSUE TITLE
Cannot install Lux v0.12.0 from scoop

### ISSUE THREAD

**Issue by topbardon** [iawia002/lux#1011]
I cannot search `Lux 0.12.0` from scoop bucket `main` but I can see `Annie v0.11.0`. 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/95011132/151703496-bc923ffb-772f-4951-ac40-f5e3203447d6.png">

**Comment by VoidxHoshi** [comment]
然而你去scoop main仓库里搜annie反而啥都没有，只有lux，你是不是仓库源错了
这个改名issue还是我提的。
https://github.com/ScoopInstaller/Main/issues/3189
https://github.com/ScoopInstaller/Main/pull/3190

**Comment by topbardon** [comment]
我到 [scoop main 的 bucket](https://github.com/ScoopInstaller/Main/tree/master/bucket) 中的确看到了 `lux.json`，但是我在进行 `scoop update` 之后发现和之前的并没有区别。我想问一下安装 `lux.exe` 是否是要安装 `wixtoolset (3.11.2) --> includes 'lux.exe'`，或者是我需要升级自己的 `'main' bucket`？
<img width="832" alt="image" src="https://user-images.githubusercontent.com/95011132/151908144-4b26864c-506c-4a4b-95b4-684f1174f602.png">

**Comment by VoidxHoshi** [comment]
> 我到 [scoop main 的 bucket](https://github.com/ScoopInstaller/Main/tree/master/bucket) 中的确看到了 `lux.json`，但是我在进行 `scoop update` 之后发现和之前的并没有区别。我想问一下安装 `lux.exe` 是否是要安装 `wixtoolset (3.11.2) --> includes 'lux.exe'`，或者是我需要升级自己的 `'main' bucket`？ <img alt="image" width="832" src="https://user-images.githubusercontent.com/95011132/151908144-4b26864c-506c-4a4b-95b4-684f1174f602.png">

你没发现你根本没更新bucket成功吗？
unable to access

**Comment by topbardon** [comment]
> 你没发现你根本没更新bucket成功吗？ unable to access

谢谢你的提醒，我已经发现了自己没有成功更新 scoop，我在网上找到的办法是运行 `git config --global http.sslVerify "false"`，之后再运行 `scoop update` 之后发现可以成功更新。
![image](https://user-images.githubusercontent.com/95011132/152354514-e5391637-7e49-436f-ac28-2f3d72f867f8.png)

<img width="416" alt="image" src="https://user-images.githubusercontent.com/95011132/152354311-7654cc36-c7db-4885-989c-5ef1456514e1.png">
