### ISSUE TITLE
Could not create process with command 'C:\Users\???\scoop\apps\lux\current\lux.exe 这个问题怎么解决阿

### ISSUE THREAD

**Issue by Rita9966** [iawia002/lux#1022]

**Comment by Pr0gger1** [comment]
I think that Your username should contain only latin letters. I have similar problem because folder of my user consists of Cyrillic

**Comment by axetroy** [comment]
请提供完整的错误信息，或者截图，否则很难判定

**Comment by Rita9966** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月23日(星期三) 上午9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iawia002/lux] Could not create process with command &#39;C:\Users\???\scoop\apps\lux\current\lux.exe 这个问题怎么解决阿 (Issue #1022)





 
请提供完整的错误信息，或者截图，否则很难判定
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
