### ISSUE TITLE
bilibili下载播放列表貌似出问题了？只能下载第一个

### ISSUE THREAD

**Issue by cnazev** [iawia002/lux#1064]
lux -p https://www.bilibili.com/video/BV1VK4y1H7BF
记得之前是可以的

**Comment by Hao4715** [comment]
给出的链接确实不能实现整个播放列表的下载。因此尝试解决这个问题。

首先说明**结论**，通过分析B站的播放列表，得出结论：B站的播放列表分为两种组织形式，第一种我将它称为“**分P**”，另一种称为“**分集**”。从url来看二者的不同点在于，前者的整个播放列表中的视频使用相同的av/bv号，通过url中的“p=_”区分不同视频；后者则是将不同的视频归到一个播放列表，不同的视频使用不同的av/bv号。这个issue给出的链接指向的视频是按照第二种方式组织的，而该项目实现的则是第一种（lux/extractors/bilibili/bilibili_test.go 中的https://www.bilibili.com/video/av16907446/ 测试样例既为第一种），不支持第二种。

**分析依据：**
对三个url进行分析：
1.  https://www.bilibili.com/video/av16907446/ ：lux/extractors/bilibili/bilibili_test.go 中的测试样例
2.  https://www.bilibili.com/video/BV1VK4y1H7BF ： 本issue中的链接
3.  https://www.bilibili.com/video/BV1B7411A7M1 ： B站随机找的播放列表（来自UP主：影视飓风）

在lux/extractors/bilibili/bilibili.go的getMultiPageData()函数中，将正则匹配后的内容输出，能够得到相应的json串。对于上面三个文件，第一种的json结构与后两种存在差异，导致无法获取到播放列表中第一个视频之外的其他视频的信息，所以只能下载到第一个视频的内容。他们的json结构分别如下：
```
//"**分P**"的json结构
{
    "aid":
    "bvid":
    "videoData": {
        "bvid":
        "aid":
        "title":
        "pages":{
            {
                "cid":
                "page":1 //该数字区分集数
                "part"
            },
            {
                "cid":
                "page":2 //该数字区分集数
                "part"
            },
        }
    }
    
}
//"**分集**"的json结构
{
    {
    "aid":
    "bvid":
    "videoData": {
        "bvid":
        "aid":
        "title":
        "pages":{ // 只有一项，说明视频未分P
            {
                "cid":
                "page":1 
                "part"
            }
        }
      "sections":{
          {
              "episodes":{ //分集，每一集不同的av/bv id
                  {
                      "aid":
                      "title":
                      "bvid":
                  }
              }
          }
      } 
    } 
}
```
正是这种差异导致对于“分集”的播放列表不能支持。
因此在代码中对相应的结构体定义、下载流程等进行了修改，并提交代码。
有不足之处欢迎指正。

**Comment by iawia002** [comment]
#1067

**Comment by jiqing112** [comment]
在B站UP主的个人主页，投稿tab上，有一个播放全部，也会生成一个播放列表。这种bo'fang'lie播放列表在html链接上似乎没什么体现。


https://space.bilibili.com/29959830/video


https://www.bilibili.com/medialist/play/29959830?from=space&business=space&sort_field=pubtime&tid=0&spm_id_from=333.999.0.0


![image](https://user-images.githubusercontent.com/17674011/163526216-206d84fb-ad56-4f1a-b8bc-e90733e21be7.png)
![image](https://user-images.githubusercontent.com/17674011/163526282-f6760d93-6ff9-462c-b409-67d6f9ed2e3e.png)
![image](https://user-images.githubusercontent.com/17674011/163526346-71bed871-c1dc-4463-9252-e590c564835c.png)

**Comment by Ushnidaye** [comment]
可以下载整个列表了吗

**Comment by imazes** [comment]
现在又不行了,同样的案例仍然不行
lux -p https://www.bilibili.com/video/BV1VK4y1H7BF
