### ISSUE TITLE
lux-0.15.0 : unable to decode nSig: unable to extract n-function name

### ISSUE THREAD

**Issue by benalb** [iawia002/lux#1086]
Installed the new release, tried it and gives this error:

[benalb@homework ~]  $ lux -i "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
Downloading https://www.youtube.com/watch?v=dQw4w9WgXcQ error:
unable to decode nSig: unable to extract n-function name
github.com/iawia002/lux/extractors/youtube.(*extractor).genPartByFormat
        /builddir/lux-0.15.0/extractors/youtube/youtube.go:135
github.com/iawia002/lux/extractors/youtube.(*extractor).youtubeDownload
        /builddir/lux-0.15.0/extractors/youtube/youtube.go:86
github.com/iawia002/lux/extractors/youtube.(*extractor).Extract
        /builddir/lux-0.15.0/extractors/youtube/youtube.go:41
github.com/iawia002/lux/extractors.Extract
        /builddir/lux-0.15.0/extractors/extractors.go:52
github.com/iawia002/lux/app.download
        /builddir/lux-0.15.0/app/app.go:271
github.com/iawia002/lux/app.New.func1
        /builddir/lux-0.15.0/app/app.go:248
github.com/urfave/cli/v2.(*App).RunContext
        /builddir/lux-0.15.0/_build-lux-xbps/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /builddir/lux-0.15.0/_build-lux-xbps/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main
        /builddir/lux-0.15.0/main.go:13
runtime.main
        /usr/lib/go/src/runtime/proc.go:250
runtime.goexit
        /usr/lib/go/src/runtime/asm_386.s:1326

**Comment by viatekh** [comment]
yeah, also experiencing this.
