### ISSUE TITLE
为什么我在哔哩哔哩下载的视频是两个文件

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1133]
能不能把音频文件和视频文件合并成为一个文件

**Comment by zero890628** [comment]
我也是这个情况

**Comment by goAug** [comment]
lux只负责下载，不负责合成·。需要额外下载ffmpeg来合成。只需要将ffmpeg放到lux目录中，lux会自动调用ffmpeg,下载完成后合并视频和音频。记得给ffmpeg设置系统环境变量“D:\lux\ffmpeg\bin“，不然ffmpeg还会报错。

**Comment by fgr178707** [comment]
懂了懂了
