### ISSUE TITLE
哔哩哔哩支持4K视频但是无法下载4K

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1134]
我问一下为什么哔哩哔哩的4K8K视频无法下载
lux -i 
解析出来只有1080P
西瓜视频可以下载4k
解析出来也有 
我现在就想问为什么哔哩哔哩4和8不能下载
命令如下:
lux -i https://www.bilibili.com/video/BV1iq4y1R7sd

**Comment by awei78** [comment]
或许，你需要B站的cookie信息，那些是会员权限

**Comment by fgr178707** [comment]
az.....

**Comment by Teapot112233** [comment]
我也出现了这样的情况 有大会员是可以解析到4k视频的 但目前不可以了 只能解析到1080p的
