### ISSUE TITLE
如何下载1080p视频哔哩哔哩(我有哔哩哔哩大会员账户)

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1199]
我问一下如何登录哔哩哔哩 然后下载1080p的视频
我没看见有命令是登录账号
我应该怎么打?
lux 哔哩哔哩链接 
然后就行了?

**Comment by backuponeday** [comment]
用cookie登录

**Comment by fgr178707** [comment]
> 用饼干登录

这样的话我应该怎么写
`$ lux -c "name=账号; name2=密码" "https://www.bilibili.com/video/av20203945"`
这个命令的话输出
error:
cookie error: 账号未登录

**Comment by fgr178707** [comment]
> 用cookie登录

咋登陆?

**Comment by aohanhongzhi** [comment]
我也想知道，直接下载的分辨率都比较小
<img width="442" alt="image" src="https://github.com/iawia002/lux/assets/37319319/422b7636-39b7-42ac-89cb-1d52104df95d">
<img width="596" alt="image" src="https://github.com/iawia002/lux/assets/37319319/7aa4edf7-acfa-44ec-be5f-a76bad55caeb">

**Comment by aohanhongzhi** [comment]
> 我也想知道，直接下载的分辨率都比较小 <img alt="image" width="442" src="https://user-images.githubusercontent.com/37319319/253783954-422b7636-39b7-42ac-89cb-1d52104df95d.png"> <img alt="image" width="596" src="https://user-images.githubusercontent.com/37319319/253783961-7aa4edf7-acfa-44ec-be5f-a76bad55caeb.png">

<img width="1728" alt="image" src="https://github.com/iawia002/lux/assets/37319319/5037fd47-4c0c-4f97-a6b0-d3816a82d080">

<img width="1728" alt="image" src="https://github.com/iawia002/lux/assets/37319319/e60c5655-1cdc-4426-8437-8827817d26ce">

<img width="1728" alt="image" src="https://github.com/iawia002/lux/assets/37319319/9df2ceb7-9303-4f01-bb5e-fbc0e1901593">
代码分析：
<img width="1728" alt="image" src="https://github.com/iawia002/lux/assets/37319319/399c5f4d-a495-460f-a0fc-20629c2d3845">
