### ISSUE TITLE
[download fail]:抖音视频下载错误，unexpected end of JSON input

### ISSUE THREAD

**Issue by w21fanfan1314** [iawia002/lux#1205]
错误如下：
Downloading https://www.douyin.com/video/7177253411694398776 error:
unexpected end of JSON input
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
	/Users/iawia002/go/src/github.com/iawia002/lux/extractors/douyin/douyin.go:61
github.com/iawia002/lux/extractors.Extract
	/Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52
github.com/iawia002/lux/app.download
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
	/Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
	/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/proc.go:250
runtime.goexit
	/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/asm_arm64.s:1270
github.com/iawia002/lux/extractors.Extract
	/Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:54
github.com/iawia002/lux/app.download
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
	/Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
	/Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
	/Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
	/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/proc.go:250
runtime.goexit
	/usr/local/Cellar/go@1.18/1.18.6/libexec/src/runtime/asm_arm64.s:1270

系统的 macos

**Comment by fgr178707** [comment]
我也遇到这个情况了 好几天前好像就这样

**Comment by 734303275** [comment]
我的报这种错误
Downloading https://www.douyin.com/video/7177253411694398776 error:
https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7177253411694398776&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333 request error: HTTP 403
github.com/iawia002/lux/request.Request
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:110
github.com/iawia002/lux/request.GetByte
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:149
github.com/iawia002/lux/request.Get
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:137
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract

**Comment by fgr178707** [comment]
> https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7177253411694398776&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333

我没看得懂你这一行是什么意思?
`https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7177253411694398776&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333 `

你这行链接有问题 request error: HTTP 403 输出了一个HTTP 403错误

**Comment by 734303275** [comment]
> > https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7177253411694398776&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333
> 
> 我没看得懂你这一行是什么意思? `https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7177253411694398776&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333 `
> 
> 你这行链接有问题 request error: HTTP 403 输出了一个HTTP 403错误

我执行了lux https://www.douyin.com/video/7177253411694398776  然后就报这个错误

**Comment by fgr178707** [comment]
> 

我刚刚测试了一下我好像懂了
lux 用的API端口是老版端口
抖音好像是换API了 然后lux 还没更新 
你可以用抖音自带的下载
在最下面联播旁边
![image](https://user-images.githubusercontent.com/109357981/224977618-6be087b0-d501-4fd0-928e-fbf9702885ef.png)

**Comment by iawia002** [comment]
fixed in #1218

**Comment by 734303275** [comment]
![image](https://user-images.githubusercontent.com/45579888/227440907-67c3ede1-fe44-4fe2-b5ec-7dd41a826088.png)
需要你重新发包
