### ISSUE TITLE
[download fail]: 已更新到最新版本0.17.0 还是无法下载抖音视频

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1209]
抖音

 Windows

https://www.douyin.com/video/7207718822277565751

`Downloading https://www.douyin.com/video/7207718822277565751 error:
https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7207718822277565751&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333 request error: HTTP 403
github.com/iawia002/lux/request.Request
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:110
github.com/iawia002/lux/request.GetByte
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:149
github.com/iawia002/lux/request.Get
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:137
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/douyin/douyin.go:56
github.com/iawia002/lux/extractors.Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52
github.com/iawia002/lux/app.download
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/proc.go:250
runtime.goexit
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/asm_amd64.s:1598
github.com/iawia002/lux/request.Request
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:112
github.com/iawia002/lux/request.GetByte
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:149
github.com/iawia002/lux/request.Get
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:137
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/douyin/douyin.go:56
github.com/iawia002/lux/extractors.Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52
github.com/iawia002/lux/app.download
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/proc.go:250
runtime.goexit
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/asm_amd64.s:1598
github.com/iawia002/lux/request.GetByte
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:151
github.com/iawia002/lux/request.Get
        /Users/iawia002/go/src/github.com/iawia002/lux/request/request.go:137
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/douyin/douyin.go:56
github.com/iawia002/lux/extractors.Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52
github.com/iawia002/lux/app.download
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/proc.go:250
runtime.goexit
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/asm_amd64.s:1598
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/douyin/douyin.go:58
github.com/iawia002/lux/extractors.Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52
github.com/iawia002/lux/app.download
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/proc.go:250
runtime.goexit
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/asm_amd64.s:1598
github.com/iawia002/lux/extractors.Extract
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:54
github.com/iawia002/lux/app.download
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270
github.com/iawia002/lux/app.New.func1
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247
github.com/urfave/cli/v2.(*App).RunContext
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /Users/iawia002/go/src/github.com/iawia002/lux/main.go:13
runtime.main
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/proc.go:250
runtime.goexit
        /usr/local/Cellar/go/1.20.2/libexec/src/runtime/asm_amd64.s:1598`

**Comment by backuponeday** [comment]
要用这个https://www.douyin.com/aweme/v1/web/aweme/detail/?aweme_id=7207804389644340539&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333连接,https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7207804389644340539&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333被block了.他好像merge的是被block的接口.

**Comment by fgr178707** [comment]
> 要用这个 `https://www.douyin.com/aweme/v1/web/aweme/detail/?aweme_id=7207804389644340539&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333` 这个被block了 `https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7207804389644340539&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333` 他好像merge的是被block的接口.

没看得懂啥意思

**Comment by backuponeday** [comment]
抖音返回的是空,所以解析失败.我找个别的项目的api,你可以看一下这个[Douyin_TikTok_Download_API](https://github.com/Evil0ctal/Douyin_TikTok_Download_API)用来对接一下就行了

**Comment by fgr178707** [comment]
> 

好的谢谢回头研究研究
