### ISSUE TITLE
无法下载哔哩哔哩视频

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1214]
报错如下
`panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/iawia002/lux/extractors/bilibili.extractBangumi({0xc00002e2d0, 0x2f}, {0xc000480000, 0x33221}, {0x0, {0x0, 0x0}, 0x1, 0x0, 0x1, ...})
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/bilibili/bilibili.go:95 +0x825
github.com/iawia002/lux/extractors/bilibili.(*extractor).Extract(0x45e525?, {0xc00002e2d0, 0x2f}, {0x0, {0x0, 0x0}, 0x1, 0x0, 0x1, {0x0, ...}, ...})
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/bilibili/bilibili.go:298 +0x19d
github.com/iawia002/lux/extractors.Extract({0xc00002e2d0?, 0x575cec?}, {0x0, {0x0, 0x0}, 0x1, 0x0, 0xa, {0x0, 0x0}, ...})
        /Users/iawia002/go/src/github.com/iawia002/lux/extractors/extractors.go:52 +0x391
github.com/iawia002/lux/app.download(0xc00014fce8?, {0xc00002e2d0, 0x2f})
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:270 +0x2f2
github.com/iawia002/lux/app.New.func1(0xc000221e40)
        /Users/iawia002/go/src/github.com/iawia002/lux/app/app.go:247 +0x69d
github.com/urfave/cli/v2.(*App).RunContext(0xc00019f1e0, {0xdafc48?, 0xc000032120}, {0xc00005c3c0, 0x2, 0x2})
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/iawia002/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main()
        /Users/iawia002/go/src/github.com/iawia002/lux/main.go:13 +0x53`

**Comment by Nathaniel-Wu** [comment]
#1213
