### ISSUE TITLE
我问一下，下载完视频提示 'bvid' 不是内部或外部命令 这是正常的吗

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1231]
这个正常吗?
提示:'bvid' 不是内部或外部命令，也不是可运行的程序或批处理文件。

![image](https://user-images.githubusercontent.com/109357981/236414521-1b72c6dd-5bc8-4415-9512-402c3d9439dd.png)

**Comment by backuponeday** [comment]
在URL两端加上 `"`

**Comment by syayys** [comment]
![E7%{I)J3J L@`756(U9NK}1](https://github.com/iawia002/lux/assets/100336946/e3a84d0f-f840-496e-a2a7-fa5412b2c993)
jiujiuw救救我 哪里出问题了 cookies用插件editthiscookies找的

**Comment by fgr178707** [comment]
> ![E7%{I)J3J L@`756(U9NK}1](https://user-images.githubusercontent.com/100336946/254309613-e3a84d0f-f840-496e-a2a7-fa5412b2c993.png) jiujiuw救救我 哪里出问题了 cookies用插件editthiscookies找的

https://github.com/kairi003/Get-cookies.txt-LOCALLY 用这个插件
