### ISSUE TITLE
我想问一下如何下载加速

### ISSUE THREAD

**Issue by fgr178707** [iawia002/lux#1238]
我想问一下如何下载加速

下载速度3MB/S~3.5MB/S

我家网速正常，能跑到30MB/S

我如果想加速下载的话，我应该输入什么指令?

我现在的命令 `lux -c 1.txt 视频链接`
我需要输入多线程吗?

**Comment by simonxiao86** [comment]
lux 可以用 aria2，rpc 方式调用（这个需要自己配置），速度会快很多。
参见文档  [aria2](https://github.com/iawia002/lux#aria2)，添加 `--aria2` 选项开启，用  `-aria2addr string` 指定 rpc 地址(默认是"localhost:6800"，如果相同就不需要这个参数)，`-aria2token string` 指定 rpc token（如果有设置 token 的话需要指定）

**Comment by fgr178707** [comment]
> lux 可以用 aria2，rpc 方式调用（这个需要自己配置），速度会快很多。
> 参见文档  [aria2](https://github.com/iawia002/lux#aria2)，添加 `--aria2` 选项开启，用  `-aria2addr string` 指定 rpc 地址(默认是"localhost:6800"，如果相同就不需要这个参数)，`-aria2token string` 指定 rpc token（如果有设置 token 的话需要指定）
> 

明天看看

**Comment by fgr178707** [comment]
> lux 可以用 aria2，rpc 方式调用（这个需要自己配置），速度会快很多。 参见文档 [aria2](https://github.com/iawia002/lux#aria2)，添加 `--aria2` 选项开启，用 `-aria2addr string` 指定 rpc 地址(默认是"localhost:6800"，如果相同就不需要这个参数)，`-aria2token string` 指定 rpc token（如果有设置 token 的话需要指定）

![Uploading image.png…]()

提示错误怎么办
