### ISSUE TITLE
下载相同标题的视频无法正确处理

### ISSUE THREAD

**Issue by gq20110204** [iawia002/lux#1246]
判断是否下载过该视频的方法似乎用的是文件名 这么做就会产生一个问题
假设有两个视频 他们的标题完全一样 下载完视频1后 视频2就直接报已存在并跳过了
就像这样↓（样本bv号 BV1z84y1p7kc 和 BV1Me4y1A7uu）
![image](https://github.com/iawia002/lux/assets/22221191/56c1015a-d228-4184-b312-7603d2489e92)
![image](https://github.com/iawia002/lux/assets/22221191/396815d4-83ec-4338-901b-893447f9c851)

建议 在处理视频文件名的时候前面加上发布时间或视频的id
暂时规避的解决方法 下载时手动指定文件名 但这样又会带来新的问题
如果这个视频恰好又有多个分p 此时使用了-p参数进行分p下载 且指定了文件名
这样就会触发新bug 直接使用指定的文件名 且不在文件名后加上P1 xxx P2 xxx 这样的分p信息
导致下载完p1后 p2就直接被丢弃不下载了

希望作者修复 谢谢！

**Comment by leehow1988** [comment]
相同的问题 #1314
