### ISSUE TITLE
[download fail]: bill bill

### ISSUE THREAD

**Issue by relifenoxiao** [iawia002/lux#1313]
billbill
2024年1月30号，
在windowS 11家庭版最新版系统上发现，
Cookie没有问题，但仍然出现cookie error，我尝试着重新提取了一次cookie，但依旧没有效果
![848a36831d7509fd7c0cdae0afe13278](https://github.com/iawia002/lux/assets/116488736/84a44c0d-afec-4cc0-b940-ae4e419d8bc6)

**Comment by dazhuangge** [comment]
我下载不能下载最高画质是怎么回事，智能下载480P

**Comment by eros520** [comment]
要有科学的环境才行

**Comment by relifenoxiao** [comment]
> 要有科学的环境才行

是指用Proxy吗，按道理，我的网络环境应该是没有发生变化的，也就是我一直开着科学的上网，虽然是规则的模式，以前可以，但近几天突然不行

**Comment by relifenoxiao** [comment]
![image](https://github.com/iawia002/lux/assets/116488736/04f5e57f-7b46-4f2c-9181-0e12484bf915)
如图，我又试着重新提取了一次cookies。虽然我之前也是提取完直接用的但是出现了像我最开始说的问题。
两种可能，要么我提取错了，要么不知道为什么失效了。
总之肯定不是软件的问题
