### ISSUE TITLE
[download fail]: LUX will skip files with same names.

### ISSUE THREAD

**Issue by lolaro7080** [iawia002/lux#1314]
When I download different videos which have a same name, the LUX will only download the first one but skip the others.
Because the file is too much, I cant to rename one by one.
How can I fix it ?

IF NOT, I wonder if the developers can add new check options of file magnitude or any other way to avoid miss-skiping only by file-name?
Besides, can developers add a rename option by add index at the last of file-name?

I think the two advises will fix the problem, if there are no working ways.

**Comment by leehow1988** [comment]
的确是这样。

命令：
` lux -p -items 1-2 https://www.bilibili.com/video/BV1iC4y1j78v/ `

效果如图

![image](https://github.com/iawia002/lux/assets/6386894/4c9577ca-4d4d-4640-b4fe-82e553c8c43f)
