### ISSUE TITLE
希望B站能支持仅下载音乐

### ISSUE THREAD

**Issue by buddingworld** [iawia002/lux#1334]
lux -c c.txt -f 80-7 --ao ep271337
当前版本下这样是不支持的，但其实下载B站视频本来就是下载下来合并的，那么仅下载音频应该本来就支持的？

**Comment by RedemptionC** [comment]
use yt-dlp

**Comment by ocfox** [comment]
Solved in #1384?

**Comment by buddingworld** [comment]
> Solved in #1384?

seems like
