### ISSUE TITLE
无法运行lux v0.24.0

### ISSUE THREAD

**Issue by HXHGTS** [iawia002/lux#1346]
操作系统：Windows11专业版64位 23H2 22631.3527
选择版本：[lux_0.24.0_Windows_x86_64.zip](https://github.com/iawia002/lux/releases/download/v0.24.0/lux_0.24.0_Windows_x86_64.zip)
问题描述：解压后在命令提示符中运行，光标闪烁，但没有任何输出，也不会自动退出，不管是否添加参数都是如此，[lux_0.23.0_Windows_x86_64.zip](https://github.com/iawia002/lux/releases/download/v0.23.0/lux_0.23.0_Windows_x86_64.zip)以及之前的都正常

**Comment by HXHGTS** [comment]
这个是之前版本的运行截图:
![image](https://github.com/iawia002/lux/assets/38959826/13a7f008-5a1b-46d7-9903-213fe0d696d4)
这个是lux_0.24.0的运行截图:
![image](https://github.com/iawia002/lux/assets/38959826/fb50fa05-9825-48ee-bb42-5c3d32bb6e64)

**Comment by arthurqiao** [comment]
我在 macOS 上遇到了同样的问题，刚开始以为是无法启动，等了 2-3 分钟就可以启动了。
启动后输出的版本号显示不正确，可以正常下载视频。

**Comment by specked2527** [comment]
同样的问题 只能降级使用

**Comment by iawia002** [comment]
Duplicates with #1340, I'm gonna close this issue and track it together in #1340
