### ISSUE TITLE
Version 0.24.0 starts up slowly

### ISSUE THREAD

**Issue by arthurqiao** [iawia002/lux#1347]
System Environment：
macOS Sonoma 14.4.1 (23E224)
Apple M2 Pro

Version 0.24.0 takes a while to start up, about 2-3 minutes，but once it's launched, everything is OK except the version number.

The version number output is incorrect, unsure if it's related.

➜  ~ lux -v

lux: version v0.0.0, A fast and simple video downloader.

**Comment by iawia002** [comment]
Duplicates with #1340, I'm gonna close this issue and track it together in #1340
