### ISSUE TITLE
哔哩哔哩如何设置下载质量

### ISSUE THREAD

**Issue by bobzhang208** [iawia002/lux#1353]

**Comment by xwxb** [comment]
-i 然后 -f

不过我也没找到去哪里登录，下载不了最高画质

**Comment by heketong** [comment]
https://becool.vip/posts/tech/%E8%8E%B7%E5%8F%96%E7%BD%91%E7%AB%99cookie/
有插件能更快获取 cookies 
然后-c "xxxxx"就好

**Comment by labadapt** [comment]
那个插件只支持Chrome，而且Chrome商店国内上不去
