### ISSUE TITLE
抖音下载时有很大机率报“unexpected end of JSON input”错误

### ISSUE THREAD

**Issue by yhdgs** [iawia002/lux#1362]
抖音下载时有很大机率报“unexpected end of JSON input”错误，3次可能只有一次成功，以下是错误信息

lux -i "https://www.douyin.com/video/7346938446839041306?previous_page=main_page&tab_name=home"
Downloading https://www.douyin.com/video/7346938446839041306?previous_page=main_page&tab_name=home error:
unexpected end of JSON input
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
        /home/runner/work/lux/lux/extractors/douyin/douyin.go:101
github.com/iawia002/lux/extractors.Extract
        /home/runner/work/lux/lux/extractors/extractors.go:54
github.com/iawia002/lux/app.download
        /home/runner/work/lux/lux/app/app.go:275
github.com/iawia002/lux/app.New.func1
        /home/runner/work/lux/lux/app/app.go:252
github.com/urfave/cli/v2.(*App).RunContext
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /home/runner/work/lux/lux/main.go:13
runtime.main
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/proc.go:271
runtime.goexit
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/asm_amd64.s:1695
github.com/iawia002/lux/extractors.Extract
        /home/runner/work/lux/lux/extractors/extractors.go:56
github.com/iawia002/lux/app.download
        /home/runner/work/lux/lux/app/app.go:275
github.com/iawia002/lux/app.New.func1
        /home/runner/work/lux/lux/app/app.go:252
github.com/urfave/cli/v2.(*App).RunContext
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
        /home/runner/work/lux/lux/main.go:13
runtime.main
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/proc.go:271
runtime.goexit
        /opt/hostedtoolcache/go/1.22.2/x64/src/runtime/asm_amd64.s:1695

**Comment by cos800** [comment]
对 我也遇到
```text
Downloading https://www.douyin.com/video/7374744435109711143 error:
unexpected end of JSON input
github.com/iawia002/lux/extractors/douyin.(*extractor).Extract
	github.com/iawia002/lux/extractors/douyin/douyin.go:101
github.com/iawia002/lux/extractors.Extract
	github.com/iawia002/lux/extractors/extractors.go:54
github.com/iawia002/lux/app.download
	github.com/iawia002/lux/app/app.go:275
github.com/iawia002/lux/app.New.func1
	github.com/iawia002/lux/app/app.go:252
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
	github.com/iawia002/lux/main.go:13
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_arm64.s:1222
github.com/iawia002/lux/extractors.Extract
	github.com/iawia002/lux/extractors/extractors.go:56
github.com/iawia002/lux/app.download
	github.com/iawia002/lux/app/app.go:275
github.com/iawia002/lux/app.New.func1
	github.com/iawia002/lux/app/app.go:252
github.com/urfave/cli/v2.(*App).RunContext
	github.com/urfave/cli/v2@v2.6.0/app.go:322
github.com/urfave/cli/v2.(*App).Run
	github.com/urfave/cli/v2@v2.6.0/app.go:224
main.main
	github.com/iawia002/lux/main.go:13
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_arm64.s:1222
```

**Comment by teraStars** [comment]
对，抖音不能下载，同样的错误
