### ISSUE TITLE
Bilibili可以获取清晰度，下载Access is denied

### ISSUE THREAD

**Issue by Lyqqt** [iawia002/lux#551]
annie -i 可以获取视频信息，加 -c 也可以获取到1080P60的会员清晰度。
但是使用 -f 或者不加参数进行下载，普通清晰度和会员清晰度都会返回Access is denied。
参数最简化了，想不出什么原因。谢谢各位了。

**Comment by chinpropped** [comment]
你好。 我也收到相同的消息。
我无法在bilibli播放列表上下载视频。

你好。
我也收到這樣的短信。
不能下載bilibili的玩家視頻。

Hello. I also get the same message.
I can't download videos on bilibli playlist.

**Comment by chinpropped** [comment]
Hello. It works again! I downloaded the latest release file.

正常運轉。
請下載最新更新。

它运作完美。
您应该下载最新更新。

**Comment by Lyqqt** [comment]
@chinpropped Thanks for your reply.

你好，我使用scoop更新到0.9.6版本，问题依然存在，下载时拒绝访问。

你好，我使用scoop更新到0.9.6版本，問題依然存在，下載時拒絕訪問。

Hello,i've updated scoop to version 0.9.6. I got the same msg when I download. Access is denied.
