### ISSUE TITLE
有下载完一个文件后执行某个脚本的命令吗？

### ISSUE THREAD

**Issue by Uzibird** [iawia002/lux#611]
想在下载完后调用一个py脚本，实现提醒功能。
目前似乎不支持？

**Comment by hexiyou** [comment]
你自己写一个脚本,然后执行这个脚本就行呀，Windows下用bat，Linux下用shell
----------------
annie http://xxxxxxxxxxx
python /path/to/example.py

**Comment by Uzibird** [comment]
> ## 你自己写一个脚本，然后执行这个脚本就行呀，Windows下用bat，Linux下用shell
> 安妮[http：// xxxxxxxxxxx](http://xxxxxxxxxxx)
> python /path/to/example.py

.......行。。。行吧，很有道理。。。

**Comment by snylonue** [comment]
`annie http://xxxxxxxxxxx && python /path/to/example.py`
应该可以这样
