### ISSUE TITLE
request.Size()导致消耗过多流量，这可能是个BUG

### ISSUE THREAD

**Issue by HaliComing** [iawia002/lux#772]
使用时，发现会调用request.Size()方法获取文件的size大小，但是此方法中`res, err := Request(http.MethodGet, url, nil, headers)`中的请求方法应当使用`http.MethodHead`而不是GET。否则，如果我下载bilibili的视频，假如它有100p，此时我执行`annie -p -i url`命令后，由于需要获取视频大小，会导致其实将所有视频都下载了一遍，因为Size方法使用的是GET请求，由于`-i`参数导致只有信息打印出来，但是并没有写入本地磁盘，但是为了打印这个信息，消耗了100G流量以及30分钟的时间。
```
// Headers return the HTTP Headers of the url
func Headers(url, refer string) (http.Header, error) {
	headers := map[string]string{
		"Referer": refer,
	}
	res, err := Request(http.MethodGet, url, nil, headers)
	if err != nil {
		return nil, err
	}
	return res.Header, nil
}

```
https://github.com/iawia002/annie/blob/67298d55aaf43d840b8d7283b0ac99736173d285/request/request.go#L171

**Comment by HaliComing** [comment]
I didn't hear back from the author, so I closed it.

**Comment by axetroy** [comment]
按理来说，文件大小只是返回的 HTTP 返回头 Content-Length，并不会真实的去下载一个文件，然后再计算大小

**Comment by SeaHOH** [comment]
根据网速和接收缓冲大小，会消耗一点点文件开头的流量，只要不继续读取就无所谓。
但如果查询的文件特别多的话，耗时是肯定的，除非并发查询。
