### ISSUE TITLE
←[31mError parsing signature tokens←[0m

### ISSUE THREAD

**Issue by jeremy-hill** [iawia002/lux#815]
I am trying to watch this video offline: https://www.youtube.com/watch?v=ExKh5mpyyHY

doing thusly: 
> \>annie https://www.youtube.com/watch?v=ExKh5mpyyHY
> Downloading ←[36mhttps://www.youtube.com/watch?v=ExKh5mpyyHY←[0m error:
> ←[31mError parsing signature tokens←[0m

Something I'm doing wrong?

**Comment by jeremy-hill** [comment]
annie -v

←[36mannie←[0m: version ←[34m0.10.3←[0m, A fast, simple and clean video downloader.

**Comment by d1y** [comment]
我下载油管视频的时候同样也遇到了,请问这个该怎么玩?

**Comment by arieller** [comment]
any news on this?

**Comment by john-black-3k** [comment]
Even video urls I have downloaded with annie several days before this error do not work now.

**Comment by Koumo-OS** [comment]
I met the same problems these days

**Comment by a8nJ** [comment]
Workaround:

~~~
PS C:\> youtubedr download https://www.youtube.com/watch?v=ExKh5mpyyHY
2020/11/11 19:39:45 download to directory .
15.70 MiB / 15.70 MiB 100 % [====================================] 0s ] 8.60 MiB/s
~~~

https://github.com/kkdai/youtube

**Comment by cybergipsy2020** [comment]
same issue

**Comment by stuartskelton** [comment]
ditto

**Comment by 89z** [comment]
https://github.com/iawia002/annie/issues/815
https://github.com/iawia002/annie/issues/839
https://github.com/iawia002/annie/issues/841
https://github.com/iawia002/annie/issues/857

**Comment by 89z** [comment]
Alternative:

~~~
youtube ExKh5mpyyHY
~~~

https://github.com/89z/mech

**Comment by zcjava** [comment]
i have same problems
