### ISSUE TITLE
url parse failed of https://weibo.com/1836384951/K1upcCwot?type=comment

### ISSUE THREAD

**Issue by flyisland** [iawia002/lux#861]
annie -d https://weibo.com/1836384951/K1upcCwot\?type\=comment

annie: version 0.10.3, A fast, simple and clean video downloader.

URL:         https://m.weibo.cn/1836384951/K1upcCwot?type=comment
Method:      GET
Headers:     http.Header{
    "User-Agent":      {"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36"},
    "Accept":          {"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},
    "Accept-Charset":  {"UTF-8,*;q=0.5"},
    "Referer":         {"https://m.weibo.cn/1836384951/K1upcCwot?type=comment"},
    "Accept-Encoding": {"gzip,deflate,sdch"},
    "Accept-Language": {"en-US,en;q=0.8"},
}
Status Code: 200
Downloading https://weibo.com/1836384951/K1upcCwot?type=comment error:
url parse failed

**Comment by flyisland** [comment]
At the same time, I can use annie to download from https://weibo.com/1642632622/K1sJttTYz?type=comment

**Comment by axetroy** [comment]
> annie -d [https://weibo.com/1836384951/K1upcCwot\?type\=comment](https://weibo.com/1836384951/K1upcCwot%5C?type%5C=comment)

This URL does not exist and I can't reproduce it.

**Comment by axetroy** [comment]
> At the same time, I can use annie to download from [weibo.com/1642632622/K1sJttTYz?type=comment](https://weibo.com/1642632622/K1sJttTYz?type=comment)

This works for. can you try again with following command:

```bash
lux "https://weibo.com/1836384951/K1upcCwot%5C?type%5C=comment"
```

**Comment by flyisland** [comment]
The original URL does not exist now.
