### ISSUE TITLE
Windows无法将Annie识别为cmdlet、函数、脚本文件或可运行程序等的名称

### ISSUE THREAD

**Issue by Itishappyto996** [iawia002/lux#874]

**Comment by lacafjh** [comment]
两种解决方案，任选其一，如果长期使用推荐第一种，临时使用推荐第二种：
1. 在系统全局环境变量的 path 里添加 Annie 所在的目录
2. 将 `annie -i VIDEO_LINK` 改为 `./annie -i VIDEO_LINK`

其实你这个问题和 Annie 本身无关。拿你下载的任意可执行文件 `FILE.exe` 来说，在 Windows 系统未把它所在目录添加到环境变量前，如果你要通过命令行运行这个可执行文件，都得在文件名前加上 `./`，否则必定报错「Windows 无法将 FILE 识别为……」。而且报错后都会告诉你如果确定要执行 ，需要把命令 
`FILE` 改成 `./FILE`

另外一个建议，在提问时，如果在正文部分加上你命令行的完整输入输出截图/文本，能帮助别人更方便的理解和解答你的问题。

**Comment by topbardon** [comment]
我在 Windows Terminal 中用 PowerShell 加载 Lux 时必须用 `.\`。
![image](https://user-images.githubusercontent.com/95011132/151702786-dbdb5ba0-63a8-4e71-aa43-0d55ee38749f.png)

而在 Terminal 中用 cmd 时则可以直接输入 `Lux`，这是为什么？
![image](https://user-images.githubusercontent.com/95011132/151702836-19428028-9be9-4f52-9b52-9a1f3c3c0f12.png)

**Comment by axetroy** [comment]
问题已被二楼解决

**Comment by topbardon** [comment]
也就是说必须在`系统变量的 Path` 添加 lux 才行，我只在 `用户变量的 Path` 下添加 lux 才会在 PowerShell 遇到`无法将 “lux” 项识别为 cmdlet、函数、脚本文件或可运行程序等的名称。`
