### ISSUE TITLE
extractor怎么用，下不了p站视频

### ISSUE THREAD

**Issue by Cu-Chu-lainn** [iawia002/lux#916]
下载phb的时候出现
Downloading [36mhttps://cn.pornhub.com/view_video.php?viewkey=ph601f794a7ca98[0m error:
[31mrequest error: Get https://cn.pornhub.com/view_video.php?viewkey=ph601f794a7ca98: dial tcp 157.240.8.41:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.[0m
'pkey' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
看不懂

**Comment by axetroy** [comment]
v0.13.0 已恢复 ph 的下载支持。

上面的错误信息是因为网络问题，无法访问到 ph，所以我关闭了 issue。
