### ISSUE TITLE
lux0.12.0被杀毒软件处理了。

### ISSUE THREAD

**Issue by studentnice05** [iawia002/lux#994]
annie能用，但是lux会被智量查杀，咋办？

**Comment by topbardon** [comment]
@studentnice05 Can you tell me how to escape the scanning from Microsoft Defender? It is blocked by Microsoft Defender to download and use Lux.

**Comment by Sanmy** [comment]
same issue! How did you fix it?

**Comment by topbardon** [comment]
> same issue! How did you fix it?

I can only exclude Lux from Microsoft Defender. Now @iawia002 seems not to solve this problem.

**Comment by Sanmy** [comment]
Maybe we need to run with the code
